/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as StoryRouteImport } from './routes/story'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OrderNowRouteImport } from './routes/order-now'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as EventsCateringRouteImport } from './routes/events-catering'
import { Route as CorporateInformationRouteImport } from './routes/corporate-information'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as IndexRouteImport } from './routes/index'

const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderNowRoute = OrderNowRouteImport.update({
  id: '/order-now',
  path: '/order-now',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCateringRoute = EventsCateringRouteImport.update({
  id: '/events-catering',
  path: '/events-catering',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateInformationRoute = CorporateInformationRouteImport.update({
  id: '/corporate-information',
  path: '/corporate-information',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/corporate-information': typeof CorporateInformationRoute
  '/events-catering': typeof EventsCateringRoute
  '/menu': typeof MenuRoute
  '/order-now': typeof OrderNowRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/story': typeof StoryRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/visit': typeof VisitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/corporate-information': typeof CorporateInformationRoute
  '/events-catering': typeof EventsCateringRoute
  '/menu': typeof MenuRoute
  '/order-now': typeof OrderNowRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/story': typeof StoryRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/visit': typeof VisitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/corporate-information': typeof CorporateInformationRoute
  '/events-catering': typeof EventsCateringRoute
  '/menu': typeof MenuRoute
  '/order-now': typeof OrderNowRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/story': typeof StoryRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/visit': typeof VisitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookie-policy'
    | '/corporate-information'
    | '/events-catering'
    | '/menu'
    | '/order-now'
    | '/privacy-policy'
    | '/story'
    | '/terms-of-use'
    | '/visit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-policy'
    | '/corporate-information'
    | '/events-catering'
    | '/menu'
    | '/order-now'
    | '/privacy-policy'
    | '/story'
    | '/terms-of-use'
    | '/visit'
  id:
    | '__root__'
    | '/'
    | '/cookie-policy'
    | '/corporate-information'
    | '/events-catering'
    | '/menu'
    | '/order-now'
    | '/privacy-policy'
    | '/story'
    | '/terms-of-use'
    | '/visit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CorporateInformationRoute: typeof CorporateInformationRoute
  EventsCateringRoute: typeof EventsCateringRoute
  MenuRoute: typeof MenuRoute
  OrderNowRoute: typeof OrderNowRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  StoryRoute: typeof StoryRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  VisitRoute: typeof VisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-now': {
      id: '/order-now'
      path: '/order-now'
      fullPath: '/order-now'
      preLoaderRoute: typeof OrderNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events-catering': {
      id: '/events-catering'
      path: '/events-catering'
      fullPath: '/events-catering'
      preLoaderRoute: typeof EventsCateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-information': {
      id: '/corporate-information'
      path: '/corporate-information'
      fullPath: '/corporate-information'
      preLoaderRoute: typeof CorporateInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CorporateInformationRoute: CorporateInformationRoute,
  EventsCateringRoute: EventsCateringRoute,
  MenuRoute: MenuRoute,
  OrderNowRoute: OrderNowRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  StoryRoute: StoryRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  VisitRoute: VisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
